Cette recette est librement inspirée de celle publiée par « [[http://www.confrerieducassoulet.com][La Grande
confrérie du cassoulet de Castelnaudary]]. »

Notez que certaines déviances — on ne saurait utiliser terme
« hérésies » à la légère dans cette région — comme le choix du [[https://www.haricot-tarbais.com][haricot
tarbais]] en lieu et place du lingot de Castelnaudary, ne seraient
probablement pas validées sur les territoires de la confrérie.

Un cassoulet n’est pas très compliqué à réaliser, mais cela ne
s’improvise pas sur un coup de tête : pour une dégustation au jour J,
il est prudent de de démarrer à J-2.

* Ingrédients pour 8-10 personnes

 - 1 cuisse de poule
 - 3 gros oignons
 - 2 clous de girofle
 - 5 belles cuisses de confit de canard. À prendre en conserve — verre
   ou métal peu importe — et non sous vide car on utilise le gras du
   confit des conserves.
 - 6-8 carottes
 - 8-10 gousses d’ail
 - 8 tranches de poitrine fumée, épaisses de 5 à 8 mm
 - 8 tranches de lard, épaisses de 5 à 8 mm
 - 1 kg de saucisse de Toulouse
 - 1,5 kg de [[https://www.haricot-tarbais.com][haricots secs tarbais]] 
 - Du laurier
 - Du thym
 - Sel
 - Poivre

* Le soir de J-2 :

1. Mettre les haricots à tremper dans 4 à 5 litres d’eau pour la nuit.

* À J-1 :

1. Égoutter les haricots
1. Les mettre dans une grande casserole d’eau froide
1. Porter à ébullition 5 minutes — pour enlever l’écume
1. Égoutter les haricots et les réserver
